### PR TITLE
adding torch backend support, better cupy support and better PredictionESN & BaseESN usage of backends

### PR DESCRIPTION
**Pull request by denisj44**
adding torch backend support, better cupy support and better PredictionESN & BaseESN usage of backends

Fast performance ahead

### CODE REVIEW

**Comment by zimmerrol** [comment]
Thanks for the PR! I think somehow the diff got broken for the files you modified in the last commit: it now appears as if you have deleted the entire file, replaced it with almost the same code, and then made the modifications... This will make it very difficult to trace back modifications in the future. Do you mind correcting this and making sure the git/GitHub diff is still working fine and really only detects your changes?

Thanks!

**Comment by jollydragon** [comment]
First of all, let me show an aplogy that I finally found I could ask a question here although it doesn't look appropriate. But sorry to tell I haven't better choice after I combed the menu of this site. Please don't mind to suggest me if there's actually one.

Please allow me to ask my question.  Just want to knonw how to regulate the dimensions of "x_train",  "y_train" and "x_test" for predictionnESN? They all should be numpy arries, correct? 

I reshaped  both "x_train",  "y_train"  into (100, 1). But got the error message "ValueError: cannot reshape array of size 0 into shape (0,newaxis)" while fitting it. 

I'm frustrated to resolve this issue after searching the internet as it looks like no other people has the issue. It's appreciated if you(Mr. Zimmerrol) can share some light.

**Comment by zimmerrol** [comment]
@jollydragon Please create a new issue to discuss your problems.

**Comment by darreal44** [comment]
> Thanks for the PR @denisj44! I think somehow the diff got broken for the files you modified in the last commit: it now appears as if you have deleted the entire file, replaced it with almost the same code, and then made the modifications... This will make it very difficult to trace back modifications in the future. Do you mind correcting this and making sure the git/GitHub diff is still working fine and really only detects your changes?
> 
> Thanks!
> 
> Edit: Yes, this was because of the line endings you used. Please use the [proper ](https://docs.github.com/en/github/using-git/configuring-git-to-handle-line-endings)line endings. To fix this, please run inside the repository
> 
> ```
> git config core.autocrlf true
> git add --renormalize .
> git commit -m "Fix line endings"
> ```

This has been done + a new optimization for numpy-scipy code.
Merry Christmas

**Comment by darreal44** [comment]
Sorry about the delay but I don't find too much time to work on this (most often during holidays)

**Comment by darreal44** [comment]
The latest scipy improvement is accelerating a lot computations without gpu... My own computations was taking 6 hours it now reduces it to 4h... I am looking to much more improvements but I am uncertain to succeed.

**Comment by darreal44** [comment]
Oh yes I am @denisj44 and @darreal44 as you can see...

**Comment by zimmerrol** [comment]
Thanks for your work @denisj44 !

**Pull request merged**
